server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true

scrape_configs:
  - job_name: demo
    static_configs:
      - targets: [localhost]
        labels:
          job: demo-log
          __path__: /tmp/demo/*.log